# Generated by Django 2.0rc1 on 2017-12-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pingback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=100)),
                ('kolibri_version', models.CharField(max_length=30)),
                ('ip_address', models.CharField(max_length=45)),
                ('platform', models.CharField(max_length=10)),
                ('python_version', models.CharField(max_length=10)),
                ('database_id', models.CharField(max_length=50)),
                ('system_id', models.CharField(max_length=50)),
                ('saved_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
