# Generated by Django 2.0rc1 on 2017-12-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pingback',
            name='system_id',
        ),
        migrations.AddField(
            model_name='pingback',
            name='mode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pingback',
            name='node_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='pingback',
            name='database_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='pingback',
            name='instance_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='pingback',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='pingback',
            name='kolibri_version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pingback',
            name='platform',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='pingback',
            name='python_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pingback',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
