# Generated by Django 2.0rc1 on 2017-12-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0002_auto_20171201_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingback',
            name='uptime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
