# Generated by Django 2.0 on 2018-01-10 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0003_pingback_uptime'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPLocation',
            fields=[
                ('ip_address', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('subdivision', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('continent_code', models.CharField(blank=True, max_length=10)),
                ('continent_name', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accuracy_radius', models.IntegerField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('time_zone', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pingback',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutritionfacts.IPLocation'),
        ),
    ]
