# Generated by Django 2.0 on 2018-01-12 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0004_auto_20180110_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pingback',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='iplocation',
            name='host',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='pingback',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nutritionfacts.IPLocation'),
        ),
    ]
