# Generated by Django 2.0 on 2018-08-27 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0006_auto_20180827_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pingback',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nutritionfacts.Instance'),
        ),
        migrations.AlterField(
            model_name='pingback',
            name='saved_at',
            field=models.DateTimeField(),
        ),
    ]
