# Generated by Django 2.0 on 2018-09-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0007_auto_20180827_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='last_mode',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
