# Generated by Django 2.0 on 2018-09-04 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0008_instance_last_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pingback',
            name='database_id',
        ),
        migrations.RemoveField(
            model_name='pingback',
            name='instance_id_old',
        ),
        migrations.RemoveField(
            model_name='pingback',
            name='node_id',
        ),
        migrations.RemoveField(
            model_name='pingback',
            name='platform',
        ),
        migrations.AlterField(
            model_name='pingback',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pingbacks', to='nutritionfacts.Instance'),
        ),
        migrations.AlterField(
            model_name='pingback',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pingbacks', to='nutritionfacts.IPLocation'),
        ),
    ]
