# Generated by Django 2.0 on 2018-09-04 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0009_auto_20180904_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pingback',
            name='python_version',
        ),
    ]
