# Generated by Django 2.1 on 2018-10-09 03:34

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0010_remove_pingback_python_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=10)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateField(blank=True, null=True)),
                ('popular', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None)),
                ('storage', models.IntegerField(blank=True, null=True)),
                ('summ_started', models.IntegerField(blank=True, null=True)),
                ('summ_complete', models.IntegerField(blank=True, null=True)),
                ('summ_kinds', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('sess_user_count', models.IntegerField(blank=True, null=True)),
                ('sess_anon_count', models.IntegerField(blank=True, null=True)),
                ('sess_user_time', models.IntegerField(blank=True, null=True)),
                ('sess_anon_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(max_length=10)),
                ('learners_count', models.IntegerField(blank=True, null=True)),
                ('learner_login_count', models.IntegerField(blank=True, null=True)),
                ('coaches_count', models.IntegerField(blank=True, null=True)),
                ('coach_login_count', models.IntegerField(blank=True, null=True)),
                ('first', models.CharField(blank=True, max_length=10)),
                ('last', models.CharField(blank=True, max_length=10)),
                ('summ_started', models.IntegerField(blank=True, null=True)),
                ('summ_complete', models.IntegerField(blank=True, null=True)),
                ('summ_kinds', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('lesson_count', models.IntegerField(blank=True, null=True)),
                ('exam_count', models.IntegerField(blank=True, null=True)),
                ('exam_log_count', models.IntegerField(blank=True, null=True)),
                ('att_log_count', models.IntegerField(blank=True, null=True)),
                ('exam_att_log_count', models.IntegerField(blank=True, null=True)),
                ('sess_user_count', models.IntegerField(blank=True, null=True)),
                ('sess_anon_count', models.IntegerField(blank=True, null=True)),
                ('sess_user_time', models.IntegerField(blank=True, null=True)),
                ('sess_anon_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'verbose_name': 'Instance'},
        ),
        migrations.AlterModelOptions(
            name='iplocation',
            options={'verbose_name': 'IP Location'},
        ),
        migrations.AlterModelOptions(
            name='pingback',
            options={'verbose_name': 'Pingback'},
        ),
        migrations.AddField(
            model_name='facilitystatistics',
            name='pingback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutritionfacts.Pingback'),
        ),
        migrations.AddField(
            model_name='channelstatistics',
            name='pingback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutritionfacts.Pingback'),
        ),
    ]
