# Generated by Django 2.1 on 2018-10-10 01:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0011_auto_20181009_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelstatistics',
            old_name='popular',
            new_name='popular_ids',
        ),
        migrations.AddField(
            model_name='channelstatistics',
            name='popular_counts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
