# Generated by Django 2.1 on 2018-10-10 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0012_auto_20181010_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelstatistics',
            old_name='summ_kinds',
            new_name='sess_kinds',
        ),
        migrations.RenameField(
            model_name='facilitystatistics',
            old_name='summ_kinds',
            new_name='sess_kinds',
        ),
    ]
