# Generated by Django 2.1 on 2018-10-11 21:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0013_auto_20181010_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitystatistics',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
