# Generated by Django 2.1 on 2018-10-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0014_facilitystatistics_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingback',
            name='language',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='pingback',
            name='timezone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
