# Generated by Django 2.1 on 2018-11-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0015_auto_20181011_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingback',
            name='installer',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pingback',
            name='server_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
