# Generated by Django 2.1 on 2019-01-19 07:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0016_auto_20181110_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msg_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('timestamp', models.DateField()),
                ('version_range', models.CharField(blank=True, max_length=50)),
                ('link_url', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('i18n', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
