# Generated by Django 2.1 on 2019-01-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0017_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='version_range',
            field=models.CharField(default='*', max_length=50),
        ),
    ]
