# Generated by Django 2.1 on 2019-01-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0018_auto_20190126_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitystatistics',
            name='first_log',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitystatistics',
            name='last_log',
            field=models.DateField(blank=True, null=True),
        ),
    ]
