# Generated by Django 2.1 on 2019-01-26 00:48

import datetime

from django.db import migrations

def convert_dates(apps, schema_editor):
    FacilityStatistics = apps.get_model('nutritionfacts', 'FacilityStatistics')
    for stats in FacilityStatistics.objects.all():
        if stats.first:
        	stats.first_log = datetime.datetime.strptime(stats.first, '%Y-%m-%d').date()
        if stats.last:
        	stats.last_log = datetime.datetime.strptime(stats.last, '%Y-%m-%d').date()
        stats.save()


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0019_auto_20190126_0041'),
    ]

    operations = [
        migrations.RunPython(convert_dates),
    ]
