# Generated by Django 2.1 on 2019-01-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0020_auto_20190126_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitystatistics',
            name='first',
        ),
        migrations.RemoveField(
            model_name='facilitystatistics',
            name='last',
        ),
    ]
