# Generated by Django 2.1 on 2019-02-27 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0021_auto_20190126_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsPingback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('saved_at', models.DateTimeField(blank=True)),
                ('pingback', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutritionfacts.Pingback')),
            ],
        ),
        migrations.AddField(
            model_name='channelstatistics',
            name='statspingback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nutritionfacts.StatisticsPingback'),
        ),
        migrations.AddField(
            model_name='facilitystatistics',
            name='statspingback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nutritionfacts.StatisticsPingback'),
        ),
    ]
