# Generated by Django 2.1 on 2019-03-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0022_auto_20190227_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='platform',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='instance',
            name='python_version',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
