# Generated by Django 2.1 on 2019-06-18 20:37

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0023_auto_20190329_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='active',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('DISABLED', 'Disabled'), ('STAGED', 'Staged'), ('ACTIVE', 'Active')], default='DISABLED', max_length=15),
        ),
        migrations.AlterField(
            model_name='message',
            name='link_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
