# Generated by Django 2.1.11 on 2019-12-18 16:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0024_auto_20190618_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthYearStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField(blank=True, null=True)),
                ('standard_deviation', models.FloatField(blank=True, null=True)),
                ('total_specified', models.IntegerField(blank=True, null=True)),
                ('deferred_count', models.IntegerField(blank=True, null=True)),
                ('not_specified_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenderStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_counts', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='channelstatistics',
            name='birth_year_stats_learners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channel_birthyearstats_learner', to='nutritionfacts.BirthYearStats'),
        ),
        migrations.AddField(
            model_name='channelstatistics',
            name='birth_year_stats_non_learners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channel_birthyearstats_nonlearner', to='nutritionfacts.BirthYearStats'),
        ),
        migrations.AddField(
            model_name='channelstatistics',
            name='gender_stats_learners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channel_genderstats_learner', to='nutritionfacts.GenderStats'),
        ),
        migrations.AddField(
            model_name='channelstatistics',
            name='gender_stats_non_learners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channel_genderstats_nonlearner', to='nutritionfacts.GenderStats'),
        ),
        migrations.AddField(
            model_name='facilitystatistics',
            name='birth_year_stats_learners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facility_birthyearstats_learner', to='nutritionfacts.BirthYearStats'),
        ),
        migrations.AddField(
            model_name='facilitystatistics',
            name='birth_year_stats_non_learners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facility_birthyearstats_nonlearner', to='nutritionfacts.BirthYearStats'),
        ),
        migrations.AddField(
            model_name='facilitystatistics',
            name='gender_stats_learners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facility_genderstats_learner', to='nutritionfacts.GenderStats'),
        ),
        migrations.AddField(
            model_name='facilitystatistics',
            name='gender_stats_non_learners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facility_genderstats_nonlearner', to='nutritionfacts.GenderStats'),
        ),
    ]
