# Generated by Django 2.1.15 on 2020-04-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0025_auto_20191218_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pingback',
            name='installer',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
