# Generated by Django 2.1.15 on 2020-06-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0026_auto_20200405_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelstatistics',
            name='anon_visitors_with_logs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channelstatistics',
            name='sess_anon_count_no_visitor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channelstatistics',
            name='users_with_logs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitystatistics',
            name='anon_visitors_with_logs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitystatistics',
            name='class_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitystatistics',
            name='group_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitystatistics',
            name='sess_anon_count_no_visitor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitystatistics',
            name='users_with_logs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
