# Generated by Django 2.1.15 on 2020-08-06 18:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0027_auto_20200625_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ips_to_include',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=list, size=None),
        ),
    ]
