# Generated by Django 2.1.15 on 2020-08-06 18:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionfacts', '0028_message_ips_to_include'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='instances_to_include',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=list, help_text='(comma-separated; leave empty to ignore instance_id)', size=None),
        ),
        migrations.AlterField(
            model_name='message',
            name='ips_to_include',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=list, help_text='(comma-separated; leave empty to ignore IP)', size=None),
        ),
    ]
